[package]
name = "pos-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
pos-foundation = { path = "../pos-foundation" }
pos-store = { path = "../pos-store" }
pos-log = { path = "../pos-log" }
ciborium = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
